---
version: "3.6"
services:
  elasticsearch:
    restart: always
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    networks: ["stack"]
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data

    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: Y9vv7D43wGGM
      ES_JAVA_OPTS: "-Xmx5g -Xms5g" # this option should be half of sever ram
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
  kibana:
    restart: always
    image: kibana:7.9.1
    container_name: kibana

    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true

    ports: ["5601:5601"]
    networks: ["stack"]
    depends_on: ["elasticsearch"]

  logstash:
    restart: always
    image: logstash:7.9.1
    container_name: logstash
    networks: ["stack"]
    depends_on: ["elasticsearch"]
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
  apm-server:
    restart: always
    image: docker.elastic.co/apm/apm-server:7.9.1
    container_name: apm_server
    ports:
      - "8200:8200"
      - "8201:8200"
    networks: ["stack"]
    command: --strict.perms=false -e # -e flag to log to stderr and disable syslog/file output
    # environment:
    #   - ELASTIC_PASSWORD=Y9vv7D43wGGM
    #   - apm-server.host=0.0.0.0
    #   - setup.kibana.host=kibana:5601
    #   - output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on: ["elasticsearch", "kibana"]
    volumes:
      - type: bind
        source: ./apm-server/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true

networks: { stack: {} }
# use docker volume to persist ES data outside of a container.
volumes:
  es_data:
  certs:
