email:
    status: true
    host: mail.myagah.com
    port: 587
    subject: alert
    auth:
        - username: elk@myagah.com
          password: E123456e@
    receivers:
        - amiralamian10@gmail.com
        - nasrollahy.hamidreza@gmail.com
    sender: elk@myagah.com
alert:
    host: https://elasticsearch
    port: 9200
    auth:
        - username: elastic
          password: o7RMngoWR4PvQYyESrRz
    ssl:
        - ca: /usr/share/elasticsearch/config/certificates/ca/ca.crt
          key: /usr/share/elasticsearch/config/certificates/alerting-app/alerting-app.key
          cert: /usr/share/elasticsearch/config/certificates/alerting-app/alerting-app.crt
    indices: test_index
sms:
    status: true
    host: alert-sms
    port: 3000
    version: 1
    URIs:
        - sendSms: sendSms
    receiver: 
      - 09214698677
      - 09120975633
      - 09216553942
job:
    time: '*/5 * * * *' #every 5 minutes

indices:
    pim-user:
        error: pim_user_error2
    messaging:
        cpu_usage: messaging_cpu_usage

