alert:
    host: https://elasticsearch
    port: 9200
    auth:
        - username: elastic
          password: Zs66gRczqhtFwkQuaaUPjMR
    ssl:
        - ca: /usr/share/elasticsearch/config/certificates/ca/ca.crt
          key: /usr/share/elasticsearch/config/certificates/alert-app/alert-app.key
          cert: /usr/share/elasticsearch/config/certificates/alert-app/alert-app.crt

email:
    status: true
    host: mail.myagah.com
    port: 587
    subject: alert
    auth:
        - username: elk@myagah.com
          password: E123456e@
    receivers:
        - sharifiansepide@gmail.com
    sender: elk@myagah.com

sms:
    status: false
    host: alert-sms
    port: 3000
    version: 1
    URIs:
        - sendSms: sendSms
    receiver: 
      - 09214698677

hardDisk:
    maxUsage: 90%

job:
    ordinaryTime: '*/5 * * * *' #every 5 minutes
    specialTime:  '* * * * *' #every 1 minute
    hardDiskTime: '* * */1 * *' #every 1 hour
  
indices:
    # apm:
    metrics:
        crypto_cpu_usage:
            index: darixo_cpu_usage_index
            isPrimary: false  
        darixo_ram_uasge:
            index: darixo_ram_usage_index
            isPrimary: false
        darixo_load:
            index: darixo_load_index
            isPrimary: false
        darixo_inbound:
            index: darixo_inbound_index
            isPrimary: false
        darixo_outbound:
            index: darixo_outbound_index
            isPrimary: false
    # Uptime:
    #     darixo_server_uptime:
    #         index: darixo_uptime_index
    #         isPrimery: true

specialIndices:
    docker:
        darixo_container_uptime:
            index: heartbeat-*
            isPrimary: true

context:
    Uptime:
        email:
            negative: '<h1 style = "color : red"> Uptime server alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">  %context_message% </p>  <p style= "font-size:14px"> %timestamp% </p> <p style= "font-size:14px"> server ip =>  %ip% </p> '
            positive: '<h1 style = "color : green"> Uptime server alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">server is up and running</p>  <p style= "font-size:14px"> %timestamp% </p> <p style= "font-size:14px"> server ip =>  %ip% </p> '
        sms: 
            negative: 'Uptime server alert  %space%%tags% %space%%context_message% %space%%timestamp%  %space%%ip%'
            positive: 'Uptime server alert  %space%%tags% %space%server is up and running %space%%timestamp%  %space%%ip%'
    metrics:
        email:
            negative: '<h1 style = "color: red">   Metrics usage alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">  %context_reason% </p>  <p style= "font-size:14px">  %timestamp% </p>  <p style= "font-size:14px"> %ip% </p>'
            positive: '<h1 style = "color: green">   Metrics usage alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">%usage%</p>  <p style= "font-size:14px">  %timestamp% </p>  <p style= "font-size:14px"> %ip% </p>'
        sms: 
            negative: 'Metrics usage alert  %space%%tags% %space%%context_reason% %space%%timestamp% %space%%ip%'
            positive: 'Metrics usage alert  %space%%tags% %space%%usage% %space%%timestamp% %space%%ip%'
    apm:
        email:
            negative: '<h1 style = "color : red"> apm server alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">  %context_message% </p>  <p style= "font-size:14px"> %timestamp% </p> <p style= "font-size:14px"> server ip =>  %ip% </p> '
            positive: ''
        sms:
            negative: 'apm server alert  %space%%tags% %space%%context_message% %space%%timestamp%  %space%%ip%'
            positive: ''
    docker:
        email:
            negative: '<h1 style = "color : red"> Docker container alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">  %context_message% </p>  <p style= "font-size:14px"> %timestamp% </p> <p style= "font-size:14px">%ip% </p> '
            positive: '<h1 style = "color : green"> Docker container alert </h1>  <p style= "font-size:14px">  %tags% </p>   <p style= "font-size:14px">containers are up and running</p>  <p style= "font-size:14px"> %timestamp% </p> <p style= "font-size:14px"> %ip% </p> '
        sms: 
            negative: 'Docker container alert  %space%%tags% %space%%context_message% %space%%timestamp%  %space%%ip%'
            positive: 'Docker container alert  %space%%tags% %space%containers are up and running %space%%timestamp%  %space%%ip%'

