---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: 631E33DFBA389C8AE7811DB2E22FDA5913
## X-Pack security credentials
#
# elasticsearch.hosts: ["https://elasticsearch:9200"]
# elasticsearch.username: kibana_system
# elasticsearch.password: TMvch3T8mLzLQvPePnnx

# elasticsearch.ssl.certificateAuthorities: [ "/usr/share/elasticsearch/config/certificates/ca/ca.crt" ]
#elasticsearch.ssl.truststore.path: "~/elk/elasticsearch/elastic-stack-ca.p12"
