---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: ["https://elasticsearch:9200"]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: 631E33DFBA389C8AE7811DB2E22FDA5913
## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: Y9vv7D43wGGM

#elasticsearch.ssl.certificateAuthorities: [ "~/elk/elasticsearch/elasticsearch-ca.pem" ]
#elasticsearch.ssl.truststore.path: "~/elk/elasticsearch/elastic-stack-ca.p12"
